-- 偶然の6人: Supabase production schema
-- Run this file in the Supabase SQL editor, or apply it with `supabase db push`.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  name text,
  department text,
  role text not null default 'member' check (role in ('member', 'office', 'maintainer')),
  interest_tags text[] not null default '{}',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.events (
  id bigint generated by default as identity primary key,
  host_id uuid not null references public.profiles(id) on delete restrict,
  theme text not null check (char_length(theme) between 1 and 100),
  sub_theme text check (sub_theme is null or char_length(sub_theme) <= 200),
  datetime timestamptz not null,
  duration_minutes integer not null default 60 check (duration_minutes between 1 and 120),
  location text not null check (char_length(location) between 1 and 200),
  location_url text check (location_url is null or location_url ~ '^https?://'),
  fee integer not null default 0 check (fee between 0 and 5000),
  capacity integer not null default 6 check (capacity between 2 and 6),
  min_participants integer not null default 2 check (min_participants between 1 and 6 and min_participants <= capacity),
  deadline date not null,
  notes text check (notes is null or char_length(notes) <= 1000),
  status text not null default '募集中' check (status in ('募集中', '実施確定', '開催済', '未実施')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.tags (
  id bigint generated by default as identity primary key,
  name text not null unique check (char_length(name) between 1 and 50)
);

create table if not exists public.event_tags (
  event_id bigint not null references public.events(id) on delete cascade,
  tag_id bigint not null references public.tags(id) on delete cascade,
  primary key (event_id, tag_id)
);

create table if not exists public.participations (
  id bigint generated by default as identity primary key,
  event_id bigint not null references public.events(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  comment text check (comment is null or char_length(comment) <= 500),
  status text not null default '申込' check (status in ('申込', 'キャンセル')),
  applied_at timestamptz not null default now(),
  cancelled_at timestamptz,
  unique (event_id, user_id)
);

create table if not exists public.reports (
  id bigint generated by default as identity primary key,
  event_id bigint not null references public.events(id) on delete cascade,
  author_id uuid not null references public.profiles(id) on delete cascade,
  type text not null check (type in ('参加者感想', '開催者報告')),
  content text not null check (char_length(content) between 1 and 2000),
  photo_url text check (photo_url is null or photo_url ~ '^https?://'),
  created_at timestamptz not null default now(),
  unique (event_id, author_id, type)
);

create table if not exists public.likes (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  target_type text not null check (target_type = 'report'),
  target_id bigint not null references public.reports(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (user_id, target_type, target_id)
);

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  type text not null,
  content text not null,
  is_read boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.feedbacks (
  id bigint generated by default as identity primary key,
  from_user_id uuid not null references public.profiles(id) on delete cascade,
  content text not null check (char_length(content) between 1 and 2000),
  event_id bigint references public.events(id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists events_datetime_idx on public.events(datetime);
create index if not exists events_host_id_idx on public.events(host_id);
create index if not exists participations_event_status_idx on public.participations(event_id, status);
create index if not exists participations_user_status_idx on public.participations(user_id, status);
create index if not exists reports_event_id_idx on public.reports(event_id);
create index if not exists notifications_user_created_idx on public.notifications(user_id, created_at desc);

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
set search_path = public, pg_temp
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists profiles_touch_updated_at on public.profiles;
create trigger profiles_touch_updated_at before update on public.profiles
for each row execute function public.touch_updated_at();

drop trigger if exists events_touch_updated_at on public.events;
create trigger events_touch_updated_at before update on public.events
for each row execute function public.touch_updated_at();

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  insert into public.profiles (id, email, name)
  values (
    new.id,
    coalesce(new.email, ''),
    nullif(coalesce(new.raw_user_meta_data ->> 'name', new.raw_user_meta_data ->> 'full_name', ''), '')
  )
  on conflict (id) do update set email = excluded.email;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert or update of email on auth.users
for each row execute function public.handle_new_user();

insert into public.profiles (id, email, name)
select id, coalesce(email, ''), nullif(coalesce(raw_user_meta_data ->> 'name', raw_user_meta_data ->> 'full_name', ''), '')
from auth.users
on conflict (id) do update set email = excluded.email;

create or replace function public.current_profile_role()
returns text
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select coalesce((select role from public.profiles where id = auth.uid()), 'member');
$$;

create or replace function public.is_office_user()
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select public.current_profile_role() in ('office', 'maintainer');
$$;

alter table public.profiles enable row level security;
alter table public.events enable row level security;
alter table public.tags enable row level security;
alter table public.event_tags enable row level security;
alter table public.participations enable row level security;
alter table public.reports enable row level security;
alter table public.likes enable row level security;
alter table public.notifications enable row level security;
alter table public.feedbacks enable row level security;

drop policy if exists profiles_read_self_or_office on public.profiles;
create policy profiles_read_self_or_office on public.profiles for select to authenticated
using (id = auth.uid() or public.is_office_user());

drop policy if exists profiles_update_self on public.profiles;
create policy profiles_update_self on public.profiles for update to authenticated
using (id = auth.uid()) with check (id = auth.uid());

drop policy if exists events_read_authenticated on public.events;
create policy events_read_authenticated on public.events for select to authenticated using (true);

drop policy if exists tags_read_authenticated on public.tags;
create policy tags_read_authenticated on public.tags for select to authenticated using (true);

drop policy if exists event_tags_read_authenticated on public.event_tags;
create policy event_tags_read_authenticated on public.event_tags for select to authenticated using (true);

drop policy if exists participations_read_own_or_host on public.participations;
create policy participations_read_own_or_host on public.participations for select to authenticated
using (
  user_id = auth.uid()
  or exists (select 1 from public.events e where e.id = event_id and e.host_id = auth.uid())
  or public.is_office_user()
);

drop policy if exists reports_read_authenticated on public.reports;
create policy reports_read_authenticated on public.reports for select to authenticated using (true);

drop policy if exists likes_read_authenticated on public.likes;
create policy likes_read_authenticated on public.likes for select to authenticated using (true);

drop policy if exists notifications_read_own on public.notifications;
create policy notifications_read_own on public.notifications for select to authenticated using (user_id = auth.uid());

drop policy if exists feedbacks_read_office on public.feedbacks;
create policy feedbacks_read_office on public.feedbacks for select to authenticated using (public.is_office_user());

-- All browser writes go through the RPC functions below. Revoke broad table access
-- so a leaked publishable key never bypasses the business rules.
revoke all on table
  public.profiles,
  public.events,
  public.tags,
  public.event_tags,
  public.participations,
  public.reports,
  public.likes,
  public.notifications,
  public.feedbacks
from anon, authenticated;

create or replace function public.deadline_at(p_deadline date)
returns timestamptz
language sql
immutable
set search_path = public, pg_temp
as $$
  select (p_deadline::timestamp + interval '1 day') at time zone 'Asia/Tokyo';
$$;

create or replace function public.effective_event_status(p_event_id bigint)
returns text
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select case
    when e.status = '未実施' then '未実施'
    when now() >= e.datetime + make_interval(mins => e.duration_minutes)
      then case when 1 + count(p.id) filter (where p.status = '申込') >= e.min_participants
        then '開催済' else '未実施' end
    when e.status = '実施確定' then '実施確定'
    when now() >= public.deadline_at(e.deadline)
      then case when 1 + count(p.id) filter (where p.status = '申込') >= e.min_participants
        then '実施確定' else '未実施' end
    else '募集中'
  end
  from public.events e
  left join public.participations p on p.event_id = e.id
  where e.id = p_event_id
  group by e.id;
$$;

create or replace function public.event_json(p_event_id bigint, p_user_id uuid default auth.uid())
returns jsonb
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select jsonb_build_object(
    'id', e.id,
    'theme', e.theme,
    'subTheme', e.sub_theme,
    'datetime', e.datetime,
    'durationMinutes', e.duration_minutes,
    'location', e.location,
    'locationUrl', e.location_url,
    'fee', e.fee,
    'capacity', e.capacity,
    'minParticipants', e.min_participants,
    'deadline', e.deadline,
    'notes', e.notes,
    'tags', coalesce((
      select jsonb_agg(t.name order by t.name)
      from public.event_tags et join public.tags t on t.id = et.tag_id
      where et.event_id = e.id
    ), '[]'::jsonb),
    'hostId', e.host_id,
    'hostName', hp.name,
    'hostDepartment', hp.department,
    'participantsCount', 1 + (select count(*) from public.participations p where p.event_id = e.id and p.status = '申込'),
    'remainingSeats', greatest(0, e.capacity - 1 - (select count(*) from public.participations p where p.event_id = e.id and p.status = '申込')),
    'status', public.effective_event_status(e.id),
    'isApplied', exists(select 1 from public.participations p where p.event_id = e.id and p.user_id = p_user_id and p.status = '申込'),
    'isHost', e.host_id = p_user_id,
    'createdAt', e.created_at
  )
  from public.events e
  join public.profiles hp on hp.id = e.host_id
  where e.id = p_event_id;
$$;

create or replace function public.replace_event_tags(p_event_id bigint, p_tags text[])
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  delete from public.event_tags where event_id = p_event_id;
  insert into public.tags(name)
  select distinct trim(tag_name)
  from unnest(coalesce(p_tags, '{}'::text[])) tag_name
  where trim(tag_name) <> ''
  on conflict (name) do nothing;

  insert into public.event_tags(event_id, tag_id)
  select p_event_id, t.id
  from public.tags t
  where t.name in (
    select distinct trim(tag_name)
    from unnest(coalesce(p_tags, '{}'::text[])) tag_name
    where trim(tag_name) <> ''
  )
  on conflict do nothing;
end;
$$;

create or replace function public.get_my_profile()
returns jsonb
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select jsonb_build_object(
    'id', p.id,
    'email', p.email,
    'name', p.name,
    'department', p.department,
    'role', p.role,
    'interestTags', to_jsonb(p.interest_tags),
    'profileComplete', coalesce(trim(p.name), '') <> '',
    'createdAt', p.created_at
  )
  from public.profiles p where p.id = auth.uid();
$$;

create or replace function public.update_my_profile(p_name text, p_department text, p_interest_tags text[])
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  if auth.uid() is null then raise exception 'ログインが必要です'; end if;
  if p_name is null or trim(p_name) = '' or char_length(trim(p_name)) > 100 then
    raise exception '氏名は1〜100文字で入力してください';
  end if;
  update public.profiles
  set name = trim(p_name), department = nullif(trim(p_department), ''), interest_tags = coalesce(p_interest_tags, '{}')
  where id = auth.uid();
  return public.get_my_profile();
end;
$$;

create or replace function public.list_events(p_status text default null, p_tag text default null, p_sort_by text default 'new')
returns setof jsonb
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select public.event_json(e.id, auth.uid())
  from public.events e
  where (p_status is null or public.effective_event_status(e.id) = p_status)
    and (p_tag is null or exists (
      select 1 from public.event_tags et join public.tags t on t.id = et.tag_id
      where et.event_id = e.id and lower(t.name) = lower(p_tag)
    ))
  order by
    case when p_sort_by = 'near' then e.datetime end asc,
    case when p_sort_by = 'seats' then e.capacity - 1 - (select count(*) from public.participations p where p.event_id = e.id and p.status = '申込') end asc,
    case when p_sort_by not in ('near', 'seats') then e.created_at end desc;
$$;

create or replace function public.get_event(p_event_id bigint)
returns jsonb
language plpgsql
stable
security definer
set search_path = public, pg_temp
as $$
declare result jsonb;
begin
  select public.event_json(p_event_id, auth.uid()) into result;
  if result is null then raise exception '会が見つかりません'; end if;
  return result;
end;
$$;

create or replace function public.create_event(
  p_theme text, p_sub_theme text, p_datetime timestamptz, p_duration_minutes integer,
  p_location text, p_location_url text, p_fee integer, p_capacity integer,
  p_min_participants integer, p_deadline date, p_notes text, p_tags text[]
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare new_id bigint;
begin
  if auth.uid() is null then raise exception 'ログインが必要です'; end if;
  if trim(coalesce(p_theme, '')) = '' then raise exception 'テーマは必須です'; end if;
  if trim(coalesce(p_location, '')) = '' then raise exception '場所は必須です'; end if;
  if p_duration_minutes not between 1 and 120 then raise exception '開催時間は2時間以内です'; end if;
  if p_fee not between 0 and 5000 then raise exception '会費は5,000円以内です'; end if;
  if p_capacity not between 2 and 6 then raise exception '定員は2〜6人です'; end if;
  if p_min_participants not between 1 and p_capacity then raise exception '最低実行人数が不正です'; end if;
  if p_deadline > (p_datetime at time zone 'Asia/Tokyo')::date then raise exception '締切日は開催日以前にしてください'; end if;

  insert into public.events (
    host_id, theme, sub_theme, datetime, duration_minutes, location, location_url,
    fee, capacity, min_participants, deadline, notes
  ) values (
    auth.uid(), trim(p_theme), nullif(trim(p_sub_theme), ''), p_datetime, p_duration_minutes,
    trim(p_location), nullif(trim(p_location_url), ''), p_fee, p_capacity,
    p_min_participants, p_deadline, nullif(trim(p_notes), '')
  ) returning id into new_id;
  perform public.replace_event_tags(new_id, p_tags);
  return public.event_json(new_id, auth.uid());
end;
$$;

create or replace function public.update_event(
  p_event_id bigint, p_theme text, p_sub_theme text, p_datetime timestamptz,
  p_duration_minutes integer, p_location text, p_location_url text, p_fee integer,
  p_capacity integer, p_min_participants integer, p_deadline date, p_notes text, p_tags text[]
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare existing public.events%rowtype;
declare active_count integer;
begin
  select * into existing from public.events where id = p_event_id for update;
  if not found then raise exception '会が見つかりません'; end if;
  if existing.host_id <> auth.uid() then raise exception '編集権限がありません'; end if;
  select count(*) into active_count from public.participations where event_id = p_event_id and status = '申込';
  if p_capacity < active_count + 1 then raise exception '現在の参加人数より定員を減らせません'; end if;
  if p_duration_minutes not between 1 and 120 or p_fee not between 0 and 5000
    or p_capacity not between 2 and 6 or p_min_participants not between 1 and p_capacity then
    raise exception '入力値が制約を超えています';
  end if;
  if p_deadline > (p_datetime at time zone 'Asia/Tokyo')::date then raise exception '締切日は開催日以前にしてください'; end if;

  update public.events set
    theme = trim(p_theme), sub_theme = nullif(trim(p_sub_theme), ''), datetime = p_datetime,
    duration_minutes = p_duration_minutes, location = trim(p_location),
    location_url = nullif(trim(p_location_url), ''), fee = p_fee, capacity = p_capacity,
    min_participants = p_min_participants, deadline = p_deadline, notes = nullif(trim(p_notes), '')
  where id = p_event_id;
  perform public.replace_event_tags(p_event_id, p_tags);
  return public.event_json(p_event_id, auth.uid());
end;
$$;

create or replace function public.delete_event(p_event_id bigint)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  if not exists(select 1 from public.events where id = p_event_id and host_id = auth.uid()) then
    raise exception '削除権限がありません';
  end if;
  delete from public.events where id = p_event_id;
end;
$$;

create or replace function public.apply_to_event(p_event_id bigint, p_comment text default null)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare event_row public.events%rowtype;
declare active_count integer;
declare participation_row public.participations%rowtype;
declare applicant_name text;
begin
  if auth.uid() is null then raise exception 'ログインが必要です'; end if;
  select * into event_row from public.events where id = p_event_id for update;
  if not found then raise exception '会が見つかりません'; end if;
  if event_row.host_id = auth.uid() then raise exception 'ホストは自分の会に申し込めません'; end if;
  if public.effective_event_status(p_event_id) <> '募集中' then raise exception 'この会は募集を終了しています'; end if;
  if now() >= public.deadline_at(event_row.deadline) then raise exception '申込締切を過ぎています'; end if;
  if now() >= event_row.datetime then raise exception 'イベントはすでに開始しています'; end if;

  select count(*) into active_count from public.participations where event_id = p_event_id and status = '申込';
  if active_count >= event_row.capacity - 1 then raise exception '定員に達しています'; end if;

  insert into public.participations(event_id, user_id, comment, status, applied_at, cancelled_at)
  values (p_event_id, auth.uid(), nullif(trim(p_comment), ''), '申込', now(), null)
  on conflict (event_id, user_id) do update
    set comment = excluded.comment, status = '申込', applied_at = now(), cancelled_at = null
  returning * into participation_row;

  select coalesce(name, email, '参加者') into applicant_name from public.profiles where id = auth.uid();
  insert into public.notifications(user_id, type, content)
  values (event_row.host_id, 'apply', applicant_name || 'さんが「' || event_row.theme || '」に申し込みました');

  return jsonb_build_object(
    'id', participation_row.id, 'eventId', participation_row.event_id,
    'status', participation_row.status, 'comment', participation_row.comment,
    'appliedAt', participation_row.applied_at
  );
end;
$$;

create or replace function public.cancel_participation(p_event_id bigint)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare event_row public.events%rowtype;
declare participant_name text;
begin
  select * into event_row from public.events where id = p_event_id for update;
  if not found then raise exception '会が見つかりません'; end if;
  if public.effective_event_status(p_event_id) in ('開催済', '未実施') then raise exception 'この会はキャンセルできません'; end if;
  if now() >= public.deadline_at(event_row.deadline) then
    raise exception '締切後はホストに直接連絡してください';
  end if;
  update public.participations set status = 'キャンセル', cancelled_at = now()
  where event_id = p_event_id and user_id = auth.uid() and status = '申込';
  if not found then raise exception '申し込みが見つかりません'; end if;

  select coalesce(name, email, '参加者') into participant_name from public.profiles where id = auth.uid();
  insert into public.notifications(user_id, type, content)
  values (event_row.host_id, 'cancel', participant_name || 'さんが「' || event_row.theme || '」への参加をキャンセルしました');
  return jsonb_build_object('message', 'キャンセルしました');
end;
$$;

create or replace function public.list_my_applications()
returns setof jsonb
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select jsonb_build_object(
    'id', p.id, 'eventId', p.event_id, 'status', p.status,
    'comment', p.comment, 'appliedAt', p.applied_at,
    'event', public.event_json(p.event_id, auth.uid())
  )
  from public.participations p
  where p.user_id = auth.uid()
  order by p.applied_at desc;
$$;

create or replace function public.list_my_hosted_events()
returns setof jsonb
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select public.event_json(e.id, auth.uid()) from public.events e
  where e.host_id = auth.uid() order by e.datetime desc;
$$;

create or replace function public.get_my_stats()
returns jsonb
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  with my_completed_events as (
    select e.id, e.host_id
    from public.events e
    where public.effective_event_status(e.id) = '開催済'
      and (e.host_id = auth.uid() or exists (
        select 1 from public.participations p where p.event_id = e.id and p.user_id = auth.uid() and p.status = '申込'
      ))
  ), people as (
    select host_id as user_id from my_completed_events
    union
    select p.user_id from public.participations p join my_completed_events e on e.id = p.event_id where p.status = '申込'
  )
  select jsonb_build_object(
    'participated', (select count(*) from public.participations where user_id = auth.uid() and status = '申込'),
    'hosted', (select count(*) from public.events where host_id = auth.uid()),
    'connections', (select count(*) from people where user_id <> auth.uid())
  );
$$;

create or replace function public.report_json(p_report_id bigint, p_user_id uuid default auth.uid())
returns jsonb
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select jsonb_build_object(
    'id', r.id, 'eventId', r.event_id, 'authorId', r.author_id,
    'type', r.type, 'content', r.content, 'photoUrl', r.photo_url,
    'authorName', coalesce(p.name, p.email, 'Unknown'),
    'likesCount', (select count(*) from public.likes l where l.target_type = 'report' and l.target_id = r.id),
    'isLiked', exists(select 1 from public.likes l where l.target_type = 'report' and l.target_id = r.id and l.user_id = p_user_id),
    'createdAt', r.created_at
  )
  from public.reports r join public.profiles p on p.id = r.author_id
  where r.id = p_report_id;
$$;

create or replace function public.list_event_reports(p_event_id bigint)
returns setof jsonb
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select public.report_json(r.id, auth.uid()) from public.reports r
  where r.event_id = p_event_id order by r.created_at desc;
$$;

create or replace function public.create_report(p_event_id bigint, p_type text, p_content text, p_photo_url text default null)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare event_row public.events%rowtype;
declare report_id bigint;
begin
  select * into event_row from public.events where id = p_event_id;
  if not found then raise exception '会が見つかりません'; end if;
  if p_type not in ('参加者感想', '開催者報告') then raise exception 'レポート種別が不正です'; end if;
  if trim(coalesce(p_content, '')) = '' or char_length(p_content) > 2000 then raise exception '内容は1〜2000文字で入力してください'; end if;
  if public.effective_event_status(p_event_id) not in ('実施確定', '開催済') then raise exception '実施確定後に投稿できます'; end if;
  if p_type = '開催者報告' and event_row.host_id <> auth.uid() then raise exception '開催者報告はホストのみ投稿できます'; end if;
  if p_type = '参加者感想' and not exists (
    select 1 from public.participations where event_id = p_event_id and user_id = auth.uid() and status = '申込'
  ) then raise exception '参加者のみ感想を投稿できます'; end if;

  insert into public.reports(event_id, author_id, type, content, photo_url)
  values (p_event_id, auth.uid(), p_type, trim(p_content), nullif(trim(p_photo_url), ''))
  returning id into report_id;
  return public.report_json(report_id, auth.uid());
exception when unique_violation then
  raise exception 'このレポートはすでに投稿済みです';
end;
$$;

create or replace function public.toggle_report_like(p_report_id bigint)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare now_liked boolean;
declare like_count bigint;
begin
  if not exists(select 1 from public.reports where id = p_report_id) then raise exception 'レポートが見つかりません'; end if;
  if exists(select 1 from public.likes where user_id = auth.uid() and target_type = 'report' and target_id = p_report_id) then
    delete from public.likes where user_id = auth.uid() and target_type = 'report' and target_id = p_report_id;
    now_liked := false;
  else
    insert into public.likes(user_id, target_type, target_id) values (auth.uid(), 'report', p_report_id);
    now_liked := true;
  end if;
  select count(*) into like_count from public.likes where target_type = 'report' and target_id = p_report_id;
  return jsonb_build_object('liked', now_liked, 'likesCount', like_count);
end;
$$;

create or replace function public.list_event_participants(p_event_id bigint)
returns setof jsonb
language plpgsql
stable
security definer
set search_path = public, pg_temp
as $$
begin
  if not exists(select 1 from public.events where id = p_event_id and (host_id = auth.uid() or public.is_office_user())) then
    raise exception '参加者一覧を閲覧する権限がありません';
  end if;
  return query
  select jsonb_build_object(
    'id', p.id, 'userId', p.user_id, 'name', pr.name,
    'department', pr.department, 'comment', p.comment, 'appliedAt', p.applied_at
  )
  from public.participations p join public.profiles pr on pr.id = p.user_id
  where p.event_id = p_event_id and p.status = '申込'
  order by p.applied_at;
end;
$$;

create or replace function public.list_notifications()
returns setof jsonb
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select jsonb_build_object(
    'id', n.id, 'type', n.type, 'content', n.content,
    'isRead', n.is_read, 'createdAt', n.created_at
  ) from public.notifications n where n.user_id = auth.uid() order by n.created_at desc;
$$;

create or replace function public.mark_all_notifications_read()
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  update public.notifications set is_read = true where user_id = auth.uid();
  return jsonb_build_object('ok', true);
end;
$$;

create or replace function public.submit_feedback(p_content text, p_event_id bigint default null)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  if trim(coalesce(p_content, '')) = '' or char_length(p_content) > 2000 then
    raise exception '内容は1〜2000文字で入力してください';
  end if;
  insert into public.feedbacks(from_user_id, content, event_id)
  values (auth.uid(), trim(p_content), p_event_id);
  return jsonb_build_object('ok', true);
end;
$$;

create or replace function public.get_office_kpi()
returns jsonb
language plpgsql
stable
security definer
set search_path = public, pg_temp
as $$
declare result jsonb;
begin
  if not public.is_office_user() then raise exception '事務局権限が必要です'; end if;
  with event_totals as (
    select e.id, public.effective_event_status(e.id) status,
      1 + (select count(*) from public.participations p where p.event_id = e.id and p.status = '申込') attendees
    from public.events e
  ), tag_totals as (
    select t.name tag, count(*)::integer count
    from public.event_tags et join public.tags t on t.id = et.tag_id
    group by t.name order by count(*) desc limit 10
  )
  select jsonb_build_object(
    'totalEvents', (select count(*) from public.events),
    'completedEvents', (select count(*) from event_totals where status = '開催済'),
    'cancelledEvents', (select count(*) from event_totals where status = '未実施'),
    'eventsThisMonth', (select count(*) from public.events where created_at >= date_trunc('month', now())),
    'totalParticipants', (select count(*) from public.participations where status = '申込'),
    'participantsThisMonth', (select count(*) from public.participations where status = '申込' and applied_at >= date_trunc('month', now())),
    'totalConnectionPairs', (select coalesce(sum(attendees * (attendees - 1) / 2), 0) from event_totals where status = '開催済'),
    'totalFeedbacks', (select count(*) from public.feedbacks),
    'topTags', coalesce((select jsonb_agg(to_jsonb(tag_totals)) from tag_totals), '[]'::jsonb)
  ) into result;
  return result;
end;
$$;

create or replace function public.list_office_feedbacks()
returns setof jsonb
language plpgsql
stable
security definer
set search_path = public, pg_temp
as $$
begin
  if not public.is_office_user() then raise exception '事務局権限が必要です'; end if;
  return query
  select jsonb_build_object(
    'id', f.id, 'content', f.content, 'fromUserName', p.name,
    'fromUserEmail', p.email, 'eventId', f.event_id,
    'eventTheme', e.theme, 'createdAt', f.created_at
  ) from public.feedbacks f
  join public.profiles p on p.id = f.from_user_id
  left join public.events e on e.id = f.event_id
  order by f.created_at desc;
end;
$$;

create or replace function public.list_office_events()
returns setof jsonb
language plpgsql
stable
security definer
set search_path = public, pg_temp
as $$
begin
  if not public.is_office_user() then raise exception '事務局権限が必要です'; end if;
  return query select public.event_json(e.id, auth.uid()) from public.events e order by e.datetime;
end;
$$;

revoke execute on function
  public.touch_updated_at(),
  public.handle_new_user(),
  public.current_profile_role(),
  public.is_office_user(),
  public.deadline_at(date),
  public.effective_event_status(bigint),
  public.event_json(bigint, uuid),
  public.replace_event_tags(bigint, text[]),
  public.get_my_profile(),
  public.update_my_profile(text, text, text[]),
  public.list_events(text, text, text),
  public.get_event(bigint),
  public.create_event(text, text, timestamptz, integer, text, text, integer, integer, integer, date, text, text[]),
  public.update_event(bigint, text, text, timestamptz, integer, text, text, integer, integer, integer, date, text, text[]),
  public.delete_event(bigint),
  public.apply_to_event(bigint, text),
  public.cancel_participation(bigint),
  public.list_my_applications(),
  public.list_my_hosted_events(),
  public.get_my_stats(),
  public.report_json(bigint, uuid),
  public.list_event_reports(bigint),
  public.create_report(bigint, text, text, text),
  public.toggle_report_like(bigint),
  public.list_event_participants(bigint),
  public.list_notifications(),
  public.mark_all_notifications_read(),
  public.submit_feedback(text, bigint),
  public.get_office_kpi(),
  public.list_office_feedbacks(),
  public.list_office_events()
from public, anon, authenticated;
grant execute on function public.get_my_profile() to authenticated;
grant execute on function public.update_my_profile(text, text, text[]) to authenticated;
grant execute on function public.list_events(text, text, text) to authenticated;
grant execute on function public.get_event(bigint) to authenticated;
grant execute on function public.create_event(text, text, timestamptz, integer, text, text, integer, integer, integer, date, text, text[]) to authenticated;
grant execute on function public.update_event(bigint, text, text, timestamptz, integer, text, text, integer, integer, integer, date, text, text[]) to authenticated;
grant execute on function public.delete_event(bigint) to authenticated;
grant execute on function public.apply_to_event(bigint, text) to authenticated;
grant execute on function public.cancel_participation(bigint) to authenticated;
grant execute on function public.list_my_applications() to authenticated;
grant execute on function public.list_my_hosted_events() to authenticated;
grant execute on function public.get_my_stats() to authenticated;
grant execute on function public.list_event_reports(bigint) to authenticated;
grant execute on function public.create_report(bigint, text, text, text) to authenticated;
grant execute on function public.toggle_report_like(bigint) to authenticated;
grant execute on function public.list_event_participants(bigint) to authenticated;
grant execute on function public.list_notifications() to authenticated;
grant execute on function public.mark_all_notifications_read() to authenticated;
grant execute on function public.submit_feedback(text, bigint) to authenticated;
grant execute on function public.get_office_kpi() to authenticated;
grant execute on function public.list_office_feedbacks() to authenticated;
grant execute on function public.list_office_events() to authenticated;

-- Bootstrap an office user after that user signs in once:
-- update public.profiles set role = 'maintainer' where email = 'you@example.com';
